version: 2.1 
orbs: 
  node : circleci/node@5.0.0
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  filters:
      branches:
        only: main
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - eb/setup
      - node/install: 
          node-version: 14.19.0
      - run:
          name: npm i ( install pakage dependencies)
          command: npm run install 
      - run:
          name: build tha udagram frontend and backend 
          command: npm run build
      - run:
          name: run test backend and frontend 
          command: npm run test 
      - run:
          name: deploy backend (host eb ) then deploy frontend on s3 
          command: npm run deploy 